// Precompile the RunConfig JSON Schema to a standalone, eval-free validator.
//
// Ajv normally compiles a schema at runtime with `new Function`, which the
// renderer's Content-Security-Policy forbids (`script-src` has no
// 'unsafe-eval', and a test enforces that). `standaloneCode` emits the same
// validator as plain ES module source instead — no eval, bundlable by Vite and
// runnable under Node.
//
// Output is committed so typecheck/test/build always have it; `npm run build`
// regenerates it first, and the output is deterministic, so a stale commit
// shows up as a diff. Re-run `npm run generate:validators` after editing the
// schema.

import Ajv from "ajv";
import addFormats from "ajv-formats";
import standaloneCode from "ajv/dist/standalone/index.js";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const APP_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA = path.join(APP_DIR, "src", "shared", "contracts", "runconfig.schema.json");
const OUT = path.join(APP_DIR, "src", "renderer", "state", "runConfigValidator.generated.js");

const schema = JSON.parse(readFileSync(SCHEMA, "utf8"));

// Same options as the former runtime `new Ajv(...)` in schemaValidation.ts, plus
// code generation as ESM source.
const ajv = new Ajv({ allErrors: true, strict: false, code: { source: true, esm: true } });
addFormats(ajv);
const validate = ajv.compile(schema);

const banner =
  "// @generated by scripts/compileSchemas.mjs from src/shared/contracts/runconfig.schema.json\n" +
  "// Do not edit by hand. Run `npm run generate:validators` after changing the schema.\n" +
  "/* eslint-disable */\n";

// Ajv still emits CommonJS `require(...)` for its runtime/format helpers even
// with code.esm, which has no meaning in the renderer's ESM bundle. Rewrite
// each into a top-level namespace import so the module is pure ESM.
let code = standaloneCode(ajv, validate);
const imports = new Map();
code = code.replace(/require\((["'])(.*?)\1\)/g, (_match, _quote, moduleId) => {
  if (!imports.has(moduleId)) imports.set(moduleId, `__ajvDep${imports.size}`);
  return imports.get(moduleId);
});
const importLines = [...imports]
  .map(([moduleId, binding]) => `import * as ${binding} from ${JSON.stringify(moduleId)};`)
  .join("\n");

writeFileSync(OUT, `${banner}${importLines}\n${code}`);
console.log(
  `Wrote ${path.relative(APP_DIR, OUT)} (${imports.size} runtime imports, eval-free)`,
);
